### PR TITLE
Use stb_image instead of lodepng to load/save images

### PR DESCRIPTION
**Pull request by zeux**
This means that we now support all formats supported by stb_image for
the purpose of transcoding. This is mostly valuable for JPEG data since
glTF content can have PNG or JPG images, and TGA data since this is a
common image interchange format for real-time graphics.

While it was technically possible to keep lodepng for saving images it
didn't seem like there's a strong reason to do so.

Note that stb libraries are compiled as part of stb_image.cpp to reduce
compile-time impact on basisu_enc.cpp.

### CODE REVIEW

**Comment by richgel999** [comment]
Unfortunately I need to get Google's permission to use this. I will start the process - please standby!

**Comment by GavinNL** [comment]
This is great! I was actually just thinking of doing this myself, but decided to check the merge requests to see if anyone has already done it!

Maybe consider using a compile time definition (USE_STB_INSTEAD) to use stb instead of lodepng, that way we have the option of using both

**Comment by zeux** [comment]
> that way we have the option of using both

Is there a reason to prefer lodepng over stb_image?

**Comment by richgel999** [comment]
> Is there a reason to prefer lodepng over stb_image?

Unfortunately we've had bug reports from one of our corporate customers that stb_image doesn't always load .PNG's reliably. lodepng has been very reliable for PNG's. I think adding stb_image for the other image formats would be fine.

**Comment by richgel999** [comment]
Please hold on - we've gotten approval for stb_dxt so getting stb_image approved shouldn't be an issue.

**Comment by zeux** [comment]
@richgel999 Just to confirm - is the current plan basically to implement JPEG & TGA loading (which are the only two formats I care about - JPEG for glTF support, and TGA because many game assets come with that) using some other libraries that unambiguously don't require binary attribution? I'd be happy with that, just trying to figure out if I should close this PR, or if I need to spend the time to rebase it to master.

**Comment by richgel999** [comment]
Yes - we cannot use stb_image because it's not fuzz-safe. It either corrupts memory, or crashes, on bad inputs. I'm implementing TGA and JPEG right now from some prior open source code of mine.

**Comment by richgel999** [comment]
Also, stb_image has failed us too many times with customers. I like the library's main idea, but its execution is lacking. There is no such thing as an "internal only" public open source image reader library IMO. Either it works for all valid inputs, and is fuzzed, or it's not.

**Pull request closed without merging**
