### PR TITLE
Standardize on cmake

### PR DESCRIPTION
**Pull request by UebelAndre**
I don't think these are all that useful and will likely degrade over time now that they're not used in CI. CMake should be able to regenerate them.

### CODE REVIEW

**Comment by UebelAndre** [comment]
I know this is a fairly invasive change but I think it's worth it for the longevity of this project. Standardizing on CMake is a good thing 😄 (imo)

**Comment by UebelAndre** [comment]
@richgel999 Are there any other remnants from other build systems in this repo I missed? I think they should all be taken care of in this PR

**Review by madebr — APPROVED** [review]
I"m no project member, but this pr looks sane to me 😄 
CMake is very superior to the msbuild file.

**Comment by UebelAndre** [comment]
@madebr do you know when @richgel999 is typically around?

**Comment by madebr** [comment]
> @madebr do you know when @richgel999 is typically around?

No idea.
This is an open source project, and something he does in his free time.
So he'll probably look at this when he feels like it.
That's open source, you should have no expectations..

**Comment by UebelAndre** [comment]
> > @madebr do you know when @richgel999 is typically around?
> 
> 
> 
> No idea.
> 
> This is an open source project, and something he does in his free time.
> 
> So he'll probably look at this when he feels like it.
> 
> That's open source, you should have no expectations..

Fair point. I'm fairly new to open source and it's hard for me to come to terms with that lol. Especially for projects I really like 😃

**Comment by richgel999** [comment]
I don't want to remove the Visual Studio build file, at least not at the moment. I develop under Visual Studio (which I've used for a quarter of a century now) and everything else is downstream (i.e. a port). I don't mind keeping the cmake and VS files in sync.

**Comment by madebr** [comment]
@UebelAndre 

You can augment appveyor.yml by building both the cmake and the visual studio solution:
```
devenv basisu.sln /Build
```

**Comment by UebelAndre** [comment]
@madebr I don't think that's a super valuable change to make. I think it's fine if people want to use msbuild but the build system in CI should be CMake to better ensure consistent behavior across the various supported platforms. That said though, that's just my opinion. I still have other PRs open I think would be beneficial and I'd love to get some eyes on those 😄

**Pull request closed without merging**
