### PR TITLE
Support outer mipmaps

### PR DESCRIPTION
**Pull request by sutongkui**
When i try to intergrate to my own engine, I hope to use the mips of my own, hope it helps for other guy

### CODE REVIEW

**Comment by richgel999** [comment]
OK - I will merge your changes into the latest repo (as far as possible). I can't use any code from the "crunch" library, so I'll rewrite that.

**Comment by richgel999** [comment]
The latest code now supports user-provided mipmap source images. See basis_compressor_params::m_source_mipmap_images. It works just like your code did.

**Comment by sutongkui** [comment]
That's great, and it will become much easier for other guys to integrate it in their own engine.

**Comment by richgel999** [comment]
Thanks for submitting this PR!

**Pull request closed without merging**
