### PR TITLE
emscripten no longer provides sys/timex.h, but does provide sys/time.h

### PR DESCRIPTION
**Pull request by walkingeyerobot**
See https://github.com/emscripten-core/emscripten/pull/17704 for details.

### CODE REVIEW

**Review by kenrussell — COMMENTED** [review]
Looks fine to me, and while I seem to have privileges to approve this, let's give Binomial a chance to review.

**Review by dschuff — COMMENTED** [review]
I think checking for emscripten instead of Wasm is better here; Wasm is the architecture and Emscripten is playing the role of the OS/SDK here. If you wanted to compile with some other Wasm SDK (e.g. wasi-sdk) in the future, it could potentially have a different set of include files.

**Comment by kenrussell** [comment]
Great catch @dschuff and thanks @walkingeyerobot for updating this.

**Comment by richgel999** [comment]
Got it - I'm reviewing.

**Comment by richgel999** [comment]
Got it thanks!

**Pull request merged**
